name: DL
channels:
  - pytorch
  - menpo
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - cairo=1.16.0
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - contourpy=1.2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - eigen=3.2.7
  - expat=2.6.2
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtorch=2.3.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvpx=1.7.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.7
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - monai=1.3.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mysql=5.7.24
  - nccl=2.22.3.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - ply=3.11
  - pybind11-abi=4
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.32.3
  - scipy=1.13.1
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.6.1
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchtriton=3.0.0
  - torchvision=0.15.2
  - tornado=6.4.1
  - tqdm=4.66.4
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - causal-conv1d==1.4.0
      - decorator==5.1.1
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - flash-attn==2.6.3
      - future==1.0.0
      - huggingface-hub==0.25.0
      - imageio==2.35.1
      - joblib==1.4.2
      - lazy-loader==0.4
      - mako==1.3.5
      - mamba-ssm==2.2.2
      - markdown==3.7
      - medcam==0.1.21
      - nibabel==5.2.1
      - ninja==1.11.1.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - pandas==2.2.2
      - pytz==2024.1
      - pywavelets==1.7.0
      - regex==2024.9.11
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - simpleitk==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.24
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchaudio==2.4.0
      - torcheval==0.0.7
      - transformers==4.44.2
      - tzdata==2024.1
